### PR TITLE
Feat: expose caching

### PR DESCRIPTION
**Pull request by woutermont**
@matthieubosquet, as requested, a local version of #234.

Seems to be the same problem?

### CODE REVIEW

**Comment by woutermont** [comment]
@matthieubosquet, what do you think?

**Comment by matthieubosquet** [comment]
@woutermont I think it looks good.

Any way you could implement a test of this feature?

**Comment by woutermont** [comment]
Tests for the tokenverifier? Does not really seem within the scope of this PR i.m.o. Behavior is the same, only the interfaces are restructured.

**Comment by matthieubosquet** [comment]
I just meant testing the override works, but I can tell it's a bit complicated to put it in and you're correct that similar tests did not exist before. Did you try this change locally?

**Comment by woutermont** [comment]
@matthieubosquet, sorry for the long wait. I have tested this as follows:

- localhost setup of community server (dpop, file backend), built with npm link to this branch of @solid/access-token-verifier
- new pod on localhost community server, with owner webid at solidcommunity.net
- read and write localhost pod data, using the penny browser

Works like a charm 🙂

**Comment by woutermont** [comment]
Bump, tagging @joachimvh

**Comment by joachimvh** [comment]
Looks fine to me

**Review by matthieubosquet — APPROVED** [review]

**Pull request merged**
